### ISSUE TITLE
reusable params with shared helper - Boolean type problem

### ISSUE THREAD

**Issue by chrisyoumans** [ruby-grape/grape#1115]
When defining a reusable parameter using a shared helper, if my parameter is of type `Boolean`, I receive a NameError. (block in <module:ParamsHelper>': uninitialized constant ParamsHelper::Boolean (NameError))

```
module ParamsHelper
  extend Grape::API::Helpers

  params :forensics do
    optional :forensics, type: Boolean, default: false, desc: "Turn forensics node on or off."
  end
end
```

All other types seem to work fine. It's as if it doesn't know where to look for the Boolean type. I even tried `type: Grape::Validations::ParamsScope::Boolean` and received: "block in <module:ParamsHelper>': uninitialized constant Grape::Validations::ParamsScope::Boolean (NameError)." I did the equivalent with String and while it threw a warning, it worked.

It's very possible I'm missing something, but considering the other types seem to work fine, I'm not sure what it could be.

**Comment by chrisyoumans** [comment]
OK, the problem goes away if I use `type: Virtus::Attribute::Boolean`. Seems a little strange considering that isn't necessary when the params are declared inside of the resource, but it works.

**Comment by rnubel** [comment]
This behavior is because that 'Boolean' constant is defined under Grape::API, [here](https://github.com/ruby-grape/grape/blob/5154b36ea924e7e17805d905c8e8e072f1cb1299/lib/grape/validations/validators/coerce.rb#L3). So it can be reached when you're inside an instance of Grape::API, but not from your module. I agree it's a little silly, though; it's always seemed weird to me that Ruby doesn't have a `Boolean` type when it has `Integer`, `String`, etc.

**Comment by dblock** [comment]
I am not sure we can do anything about this, closing.
