### ISSUE TITLE
Automatic urldecode for url params

### ISSUE THREAD

**Issue by FlorinAsavoaie** [ruby-grape/grape#1213]
I think that the expected behavior when using url params would be that they are automatically unescaped:

```ruby
params do
  requires :name, type: String
end
get ':name' do
  present {name: params[:name]} # Outputs "Firstname+Lastname", I would expect "Firstname Lastname"
end
```

This is simply calling URI.decode_www_form_component when the param is used in an URL.

**Comment by dm1try** [comment]
>url params would be that they are automatically unescaped

Yes they are.
But here your `name` param is part of URL path. It's not the form param. You should use `%20` to replace a space instead of `+`. BTW the `+` is only replaced if the content type is `application/x-www-form-urlencoded`, see [this for more information](http://www.w3.org/TR/html4/interact/forms.html#h-17.13.4.1). 

Feel free to re-open.
