### ISSUE TITLE
Error id is invalid on get route

### ISSUE THREAD

**Issue by Goundar** [ruby-grape/grape#1352]
Hi, i've an issue :'(

In this configuration, the route `nearby_missions` doesn't work and grape kick me with an error :
```
{
error: "id is invalid"
}
```

```
resource :missions do
  desc "Return a mission."
  params do
    requires :id, type: Integer, desc: "Mission id."
  end
  route_param :id do
    get do
      authenticate!
      Mission.find(params[:id]
    end
  end

  desc "Return nearby missions."
  params do
    requires :latitude, type: Float#, values: -90.0..+90.0
    requires :longitude, type: Float#, values: -180.0..+180.0 
  end
  get 'nearby_missions' do
    authenticate!
    Mission.nearby_missions(params[:latitude], params[:longitude],params[:options])
  end
end
```

but with this configuration everything is ok.

```
resource :missions do

 desc "Return nearby missions."
  params do
    requires :latitude, type: Float#, values: -90.0..+90.0
    requires :longitude, type: Float#, values: -180.0..+180.0 
  end
  get 'nearby_missions' do
    authenticate!
    Mission.nearby_missions(params[:latitude], params[:longitude],params[:options])
  end

  desc "Return a mission."
  params do
    requires :id, type: Integer, desc: "Mission id."
  end
  route_param :id do
    get do
      authenticate!
      Mission.find(params[:id]
    end
  end
end
```

I don't understand why the position of this code affects my API. 

Someone would have any idea ?

Thx !

**Comment by dblock** [comment]
This is because the parameter type is not part of route requirements. 

When you make a request like `GET nearby_missions`, Grape evaluates routes in order, so with two routes, `/:id` and `/nearby_missions`, it matches `/:id` first, making `id=nearby_missions`. Then it tries to coerce `nearby_missions` into an Integer which fails, and you get the missing id error.

You could "fix" this by adding `requirements: /\d*/` to the first route (didn't test), but you're probably just better off ordering them in the order you want them to be evaluated, which is what you did.

Hope this helps. Please do try to use the mailing list for questions!

**Comment by r-a-o** [comment]
This issue really bugs me sometimes. Is there no smart way to avoid this route confusion? 
What if we check all the possible /strings first and then do the /:id match?

**Comment by dblock** [comment]
That would completely change the behavior of things, but I suppose a feature that lets you plug a custom router wouldn't be out of question.
