### ISSUE TITLE
include_missing should have been default to true?

### ISSUE THREAD

**Issue by phuongnd08** [ruby-grape/grape#1383]
Could some one shed some light on why declared by default would return a hash with nil value on missing keys? Why is it desirable? For example, I am implementing a simple update action that collect params and then call `Model.update(declared(params))`. But by doing that, the missing field would override the the model attributes with nil. Shouldn't it just leave the model attributes intact?

By using `declared(params, include_missing: false)`, I would get the behavior I want, but curious why this is not the default behavior? isn't it less surprised to have `include_missing` default to `false` instead of `true`: https://github.com/ruby-grape/grape/blob/master/lib/grape/dsl/inside_route.rb#L30

**Comment by dblock** [comment]
It's entirely historical, that is the original implementation didn't carry the `include_missing` option, and we wanted to preserve backward compatibility. I don't think flipping it around is a great idea without renaming the method, since it will break most users silently.

I'll close this. Please use [the Grape mailing list](https://groups.google.com/forum/#!forum/ruby-grape) for questions.
