### ISSUE TITLE
Null parameter invalid with `allow_blank: true` and `values: [...]`

### ISSUE THREAD

**Issue by wolfemm** [ruby-grape/grape#1410]
The following will not accept a null/blank value:

```
requires :status, type: String, allow_blank: true, values: %w[watching considering skipping]
```

And using `values: ["watching, "considering", "skipping", nil]` fails with Grape::Exceptions::IncompatibleOptionValues.

Is this the intended behavior or a bug?

**Comment by dblock** [comment]
This is by design. The `allow_blank = true` option is a more deterministic way of allowing a `nil` value in `values`. They are synonymous and `nil` is not of type `String`.

I'll close this. Reopen if this doesn't make sense. Please use [the Grape mailing list](https://groups.google.com/forum/#!forum/ruby-grape) for questions.
