### ISSUE TITLE
error! method returns wrong content type "text/html" for 404 status code

### ISSUE THREAD

**Issue by khelll** [ruby-grape/grape#1515]
When I do:

`error!({message: 'no data'}, 404)` or even simple one `error!({}, 404)`

I always get `text/html` for content-type with the response:

`"<!DOCTYPE html>\n<html>\n<head>\n  <style type=\"text/css\">\n  body { text-align:center;font-family:helvetica,arial;font-size:22px;\n    color:#888;margin:20px}\n  #c {margin:0 auto;width:500px;text-align:left}\n  </style>\n</head>\n<body>\n  <h2>Sinatra doesn&rsquo;t know this ditty.</h2>\n  <img src='http://localhost:7777/__sinatra__/404.png'>\n  <div id=\"c\">\n    Try this:\n    <pre>get '/api/customers/111/info' do\n  \"Hello World\"\nend\n</pre>\n  </div>\n</body>\n</html>\n"`

However, if I change to any other status code like `error!({}, 500)`, it returns the expected JSON response.

**Comment by dblock** [comment]
Looking at the HTML I think this is caught by Sinatra. I would dig there next. Maybe try to build a quick repro? We could also use something similar on top of sinatra to https://github.com/ruby-grape/grape-on-rack and https://github.com/ruby-grape/grape-on-rails, so if you make a basic grape-on-sinatra implementation we can move it into the ruby-grape org and use it as a place to debug similar things. Maybe based on https://github.com/katgironpe/sinatra-pg-grape (without a database).

**Comment by nbulaj** [comment]
Hi @khelll. It is definitely the problem of Sinatra gem, not Grape. So take a look one again at your routes and rescuers. Without some code gist it is hard to understand what is going on.

**Comment by korobochek** [comment]
Hi, it looks like this is not a Sinatra issue. I have been byebugging exactly the same problem, at it looks like the issue originates here: https://github.com/ruby-grape/grape/blob/152fa4045af039a736dedb046be3a01d19af904a/lib/grape/middleware/base.rb#L69. 

If you are not explicitly overwriting `Grape::Env::API_FORMAT` anywhere, it will be set to `:txt`. In this case, if in your api config you have defined `content_type`, i.e. we have `content_type :json, 'application/hal+json; format :json`; when we are trying to evaluate `env[Grape::Env::API_FORMAT] || options[:format]` we will always get `:txt`, even though we have attempted to overwrite this with `format :json` configuration. And, since you have defined your `content_type :json, 'application/hal+json`, when you are trying to call `content_type_for(env[Grape::Env::API_FORMAT] || options[:format])` it will return `nil`, since there are no matching `:txt` definition in your configuration. This, in turn, will return content-type  as `text/html` as a default value from [line 69 in grape/lib/grape/middleware/base.rb] (https://github.com/ruby-grape/grape/blob/152fa4045af039a736dedb046be3a01d19af904a/lib/grape/middleware/base.rb#L69)

**Comment by dblock** [comment]
Closing this, a repro would be a start if you need help @khelll.

**Comment by jonmchan** [comment]
I ran into this today... It indeed is a setup issue. It is highly dependent on how you set up integrating grape and sinatra. For myself, I was able to fix this by changing the order of loading grape and sinatra in config.ru:

From:
```
run Rack::Cascade.new [API::Base, SinatraApp]
```

to:

```
run Rack::Cascade.new [SinatraApp, API::Base]
```

This caused the 404 to be intercepted by sinatra but be the last and final output in the middleware chain. Hope this helps someone else in this situation if you're using the same rack setup as mine!

**Comment by dblock** [comment]
Want to write an integration test for this @jonmchan?

**Comment by jonmchan** [comment]
@dblock it isn't a sinatra or a grape issue per se... this is a configuration issue. If you set sinatra downstream to grape, Sinatra will pick up all 404s and answer them. I think it is sufficient enough to leave this issue documented and the configuration instructions to solve it on this page.

**Comment by dblock** [comment]
Do we need a doc update for https://github.com/ruby-grape/grape#alongside-sinatra-or-other-frameworks?

**Comment by jonmchan** [comment]
@dblock yes - with the exact example in the doc, 404 would not be properly raised and caught by sinatra. You need change run `Rack::Cascade.new [API, Web]` to `run Rack::Cascade.new [Web, API]`.

Here's example code:
```
# Example config.ru

require 'sinatra'
require 'grape'

class API < Grape::API
  get :hello do
    { hello: 'world' }
  end
  get '/test_404' do
    error!({error: "message"}, 404)
  end
end

class Web < Sinatra::Base
  get '/' do
    'Hello world.'
  end
end

use Rack::Session::Cookie
#run Rack::Cascade.new [API, Web]
run Rack::Cascade.new [Web, API]
```

With API first:

```
$ curl localhost:9292/test_404
::1 - - [07/Jul/2020:12:48:07 -0500] "GET /test_404 HTTP/1.1" 404 501 0.0423
<!DOCTYPE html>
<html>
<head>
  <style type="text/css">
  body { text-align:center;font-family:helvetica,arial;font-size:22px;
    color:#888;margin:20px}
  #c {margin:0 auto;width:500px;text-align:left}
  </style>
</head>
<body>
  <h2>Sinatra doesn’t know this ditty.</h2>
  <img src='http://localhost:9292/__sinatra__/404.png'>
  <div id="c">
    Try this:
    <pre># in config.ru
class Web
  get &#x27;&#x2F;test_404&#x27; do
    &quot;Hello World&quot;
  end
end
</pre>
  </div>
</body>
</html>
```

With Web first:
```
$ curl localhost:9292/test_404
::1 - - [07/Jul/2020:12:48:45 -0500] "GET /test_404 HTTP/1.1" 404 19 0.0422
{"error":"message"}
```

**Comment by dblock** [comment]
Appreciate if you could PR this @jonmchan
