### ISSUE TITLE
Parameter maximum value

### ISSUE THREAD

**Issue by CharlesP** [ruby-grape/grape#1535]
When adding a parameter (i.e. per_page), is there a way to set the maximum value?

The cleanest (only) way I've found so far is to pass the entire array of possible options:
`optional :per_page, values: [*1..100], default: 10, type: Integer`

Is there a better way to achieve this?

**Comment by dblock** [comment]
I'll label this as a feature request to support `min` and `max`, obviously there be dragons for non enumerable types ;)

**Comment by jlfaber** [comment]
#1568 added a new feature to the ValuesValidator that allows a Proc to be supplied for anonymous custom validations.  Using this, your example above might look like this.
```ruby
optional :per_page, values: { proc: ->(v) { v.positive? && v <= 100 } }, default: 10, type: Integer
```
I should note that the ValuesValidator already accepted Ranges, so you also could have done this.
```ruby
optional :per_page, values: 1..100, default: 10, type: Integer
```
For both your original example and my Range alternative, the validator will call `include?` on the passed value.  And, in both cases, that could result in up to 100 individual tests as it enumerates the Array or Range to determine whether the supplied value is a member.  This is probably not catastrophic with a relatively small Range, but doing something like 0..1000000 could cause some performance problems.

A way to avoid this is (again) to use `proc` to test using `cover?` instead of `include?`, which will instead check that the value is between the endpoints of the range.
```ruby
optional :per_page, values: { proc: ->(v) { (1..100).cover? v } }, default: 10, type: Integer
```

**Comment by dblock** [comment]
Should we close this?

**Comment by CharlesP** [comment]
@jlfaber Thanks, that's a big help.

@dblock Yes, this looks like a valid workflow for this.
