### ISSUE TITLE
Creating an array of objects

### ISSUE THREAD

**Issue by askl56** [ruby-grape/grape#1630]
Hey all,

What's the easiest way of creating an array of objects using grape, so for example,

```ruby
  namespace :communities do
    desc 'Create an array of communities', is_array: true, entity: Entities::Community
    params do
      requires :communities, type: Array[JSON], desc: 'An Array of communities' do
        requires :community, type: Hash do
          requires :name, type: String, desc: 'Name of community'
          requires :type, type: String, desc: 'Type of community'
          requires :description, type: String, desc: 'Description of community'
        end
      end
    end
    
    post do
      params[:communities].each do |community|
        Community.create!(
          name: community['name'],
          type: community['type'],
          description: community['description'],
        )
      end
    end
  end
```

If I wanted to create an array of communities, then what would be the correct way of doing that within grape?

**Comment by dblock** [comment]
That's a bit of an open question. Is `Community` an ActiveRecord class? A Mongoid object? 

Generally this isn't great API design because if creating the 3rd community fails you're now stuck in a partial state.

I'll close this. Please use [the Grape mailing list](https://groups.google.com/forum/#!forum/ruby-grape) for questions.
