### ISSUE TITLE
Can't set cookie via API endpoint

### ISSUE THREAD

**Issue by zauzaj** [ruby-grape/grape#1772]
Hi, 

I have to set secure & http_only cookie from BE for master domain - `website.com` where those cookies will be also used by subdomains - `sub1.website.com`, `sub2.website.com` etc ... 

I've tried with `cookies`, `headers['Set-Cookie]` but nothing works as expected. Is there any other way to do it via GrapeAPI ? 

Any help would be appreciate.

Thanks

**Comment by zauzaj** [comment]
@dblock Do you have any opinion here pls ?

**Comment by dblock** [comment]
Can you please define "nothing works as expected". What are you seeing in terms of `set-cookie` line(s) emitted from the API and what do you expect to see?

**Comment by zauzaj** [comment]
@dblock Hi, seems that it was kind of wrongly configured. I'm still not sure why, but as we're dealing with subdomains, FE app had to include `withCredentials: true` or cookies wont be included in request. That's weird but that's how it is. 

Anyway it works as expected now. 

I have another question here, is there any way to spec cookies which are set from Grape endpoint. I see in gem there is no specs. 

@dblock Any hint ? 

Best Regards,
Bojan

**Comment by dblock** [comment]
There're definitely specs for cookies, [here](https://github.com/ruby-grape/grape/blob/2dcef9af4dd483a1a3d56cbfd660056ed8e9fe42/spec/grape/endpoint_spec.rb#L157). We could always use more, feel free to PR.

With RSpec, `response.cookies` should be working AFAIK.

I'll close this since the original issue was resolved. Please try to use [the Grape mailing list](https://groups.google.com/forum/#!forum/ruby-grape) for questions.
