### ISSUE TITLE
Standalone params validation for custom methods?

### ISSUE THREAD

**Issue by Kroid** [ruby-grape/grape#1797]
Hi. I searching gem for params validation. Not only for HTTP API but for the custom class methods. Grape's validations look great but available only for grape API code.

Maybe someone already extracted grape's validation in another stand-alone gem?

**Comment by dblock** [comment]
Grape validation is primarily implemented using [Virtus](https://github.com/solnic/virtus) plus some custom options like `except` or `mutually_exclusive`. I think you just want Virtus for class methods.

I'll close since it's not a Grape feature per-se. If you think something is extractable, go for it and we'd gladly adopt the dependency instead.
