### ISSUE TITLE
Strict enforcement/requiring of a param from body only

### ISSUE THREAD

**Issue by ggwc82** [ruby-grape/grape#1845]
I'm currently using `params do..requires` within my namespaces for certain params and this is working fine.

However, for one param, I decided to move it to the body as JSON, as it would possibly breach the url character limit (of ~2000). However, when testing this, it seems theres no way to specify that this comes only from the body and not as a normal param.

Is there any way that I can strictly enforce that a param is specified in the body only?

**Comment by dblock** [comment]
My first question would be "why would you want to do that"? The parameter parsing is pretty strict and well understood in general.

Parameters are automatically populated, and it depends on the content-type.

If you are POSTing JSON with a content-type of application/json, the body gets parsed and merged into params. There's no way to disable this behavior currently AFAIK and it is not something that I would recommend because all kinds of browser and other behavior expects this. Similarly something that is in a query vs. in a multipart body needs to appear predictably in params. 

You can read the body "as is" via `env['api.request.body']`, and therefore do all kinds of custom stuff.

I'll close this, but feel free to ask more questions if this doesn't answer it.
