### ISSUE TITLE
JSON errors get escaped

### ISSUE THREAD

**Issue by Kukunin** [ruby-grape/grape#1859]
I have a simple API   

```ruby
  class Root < Grape::API
    content_type :json, 'application/json; charset=UTF-8'
    default_format :json

    rescue_from ActiveRecord::RecordNotFound do
      error!({ error: :not_found }, 404)
    end
  end
```

When an `ActiveRecord::RecordNotFound` is raised, I expect my API returns `"{"error":"not_found"}` as JSON, but it retures `{&quot;error&quot;:&quot;not_found&quot;}`

It worked well in `1.0.3` version but broken in `1.1.0`

Is there any workaround for it?

It's related to #1763

**Comment by dblock** [comment]
What is the content-type returned in the error response @Kukunin? I am going to guess it's `text/plain`. 

Your default format for when the content type is not specified is `json`, but your default format otherwise is not. Without testing, I would try either adding `format :json` or `default_error_formatter :json`. Does that make a difference?

**Comment by Kukunin** [comment]
You were right. The content-type was 'text/html'. Replacing `default_format :json` to `format :json` helped, and not everything is fine

**Comment by dblock** [comment]
Happy to help. Let's close this.
