### ISSUE TITLE
Autoload error in 1.2.5 after upgrading to Rails 5.2

### ISSUE THREAD

**Issue by subvertallchris** [ruby-grape/grape#1996]
After upgrading from Rails 5.1 to 5.2, I was unable to load Rails console due to autoloading errors:

```
vendor/cache/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:205:in `guess_for_anonymous': Movement cannot be autoloaded from an anonymous class or module (NameError)
```

I reviewed a similar issue, #1815, but this was past that issue's resolution.

The problem ended up being the use of ActiveRecord model constants within `params` blocks:

```ruby
params do
  optional :plane, type: String, values: Movement.planes.keys
end
```

Just changing that `Movement.planes.key` to `::Movement.planes.keys` did the trick. What was most frustrating was that the stack trace didn't give me any help, I had to add some logging to `api.rb` in Grape to see how far it was getting.

**Comment by dnesteryuk** [comment]
I am sorry, but I don't think it is related to Grape :thinking: If you have issues with loading your classes in Rails, require them explicitly

```ruby
require Rails.root.join('app/models/movement')
```
:slightly_smiling_face:

**Comment by subvertallchris** [comment]
That’s ok, I wasn’t sure that it was Grape’s problem or fixable, thought I’d put it out there just in case and offer the workaround for posterity. I had a lot of problems upgrading Grape recently due to the remountable API, this seemed like it was in the same ballpark.

Thanks for the quick reply.

**Comment by GCorbel** [comment]
@dnesteryuk I had a similar issue. I have this class : 

```
class API < Grape::API
  # ...
  mount WebAPI
  # ...
end
```

And 
```
class WebAPI < Grape::API
  helpers JwtIdentities
end
```

It requires the module `JwtIdentities` which is located in `app/api/helpers/jwt_identities.rb`. `autoload_paths` is set correctly, but when I run the application, I have this error : 

```
JwtIdentities cannot be autoloaded from an anonymous class or module (NameError)
```

I inspected a little more and I saw that's because `WebAPI.anonymous?` returns `true` and `Grape::API::NON_OVERRIDABLE.include?(:anonymous?)` returns `false`. On my app, when [this code](https://github.com/ruby-grape/grape/blob/v1.3.0/lib/grape/api.rb#L11) is run, `Class.new.methods` doesn't include the method `:anonymous?`. 

This was because, in the `Gemfile`, Grape is before Rails. The quick solution was to move Grape after Rails. I'm not sure what's the best solution but I think, at least, a note have be added in the Readme.
