### ISSUE TITLE
Response is in wrong locale when 'present' is inside 'I18n.with_locale'

### ISSUE THREAD

**Issue by mcfoton** [ruby-grape/grape#2056]
Not sure if Grape issue, would love to get a direction. Throwing as much details as I can:

Stack is Rails + Grape + Grape Entity + Mobility. I want the response to be rendered in `en` locale while `I18n.default_locale = 'he'`. I don't want to change global I18n.locale, but scope it to each request.

My API endpoint looks like
```
I18n.with_locale('en') do
  present @post, with: V1::Entities::Post::Base
end
```
`post.name` is a Mobility translated field, stored as JSON in the db

I stil want to use the block version to scope the locale change to request, but as an experiment I've tried also to set I18n in `before` and reset in `finally`, but what I found is I get the response in the locale set in `finally`. So if I reset it to 'he' — I'll get response in 'he' locale.

I also follow Grape's `present` method to `body` and I don't see anything after that. So,  I thought, I should see here what is returned in the response.

```
def body(value = nil)
  if value
    @body = value
  elsif value == false
    @body = ''
    status 204
  else
    instance_variable_defined?(:@body) ? @body : nil
  end
end
```
And if I print the `value` from here — it is `#<V1::Entities::Post::Base:70259928978620 id=123 name=`EnglishName`>` with proper english value.

I'm confused. It's as if after the `present` something comes in and changes the locale and the value again to a default locale. 

Again, not sure if it's a bug in Grape. Any thoughts\directions would be much appreciated.

**Comment by dnesteryuk** [comment]
@mcfoton Our project uses the same approach and it works I've just checked :wink: 

```ruby
  I18n.with_locale(params[:locale] || I18n.default_locale) do
    present :cities, City.all
  end
```

However, we don't use Grape Entity there.

**Comment by dnesteryuk** [comment]
@mcfoton I would recommend to create a Rails project where you can reproduce this issue and share with maintainers. Otherwise, I am afraid, the scope is too specific.

**Comment by mcfoton** [comment]
@dnesteryuk thank you so much for the prompt reply and for checking things for me.

I've created a [demo project](https://github.com/mcfoton/rails-sandbox), it's standard Rails and two gems: `grape` and `mobility`.

```
localhost:3000/api/posts?locale=en
```
 will respond 

```
{
    "id": null,
    "title": "HE"
}
```

while expected response would be
```
{
    "id": null,
    "title": "EN"
}
```

Please tell if I can provide anything else \ improve on the example.

**Comment by mcfoton** [comment]
Did some more tinkering, doesn't seem like a grape bug after all. 

```
localhost:3000/api/posts?locale=en
```

```
resource :posts do
      desc 'Return all posts'
      get do
        post = Post.new
        post.title_he = 'HE'
        post.title_en = 'EN'

         I18n.with_locale(params[:locale]) do
          present post
         end
      end

end
```
results in ` "title": "HE"` (wrong)

while
```
resource :posts do
      desc 'Return all posts'
      get do
        post = Post.new
        post.title_he = 'HE'
        post.title_en = 'EN'

          Mobility.locale = params[:locale]
          present post
      end

 end
```
results in ` "title": "EN"` (good)

**Comment by dnesteryuk** [comment]
@mcfoton We got the same problem in our production :smile: 

The solution:

```ruby
I18n.with_locale(params[:locale]) do
  present post, serializable: true
end
```

If `serializable` isn't given, Grape entity only initializes objects inside `with_locale` then outside of the block the initialized objects get converted to the hash. So, attributes get prepared outside of `with_locale` :wink:

**Comment by thedarkside** [comment]
Stumbled upon this now and i dont see why the "solution" @dnesteryuk is a proper solution. The issue is buried in how `present` works with GrapeEntity. In my observation the entity is evaluated very late. In fact it is being evaluated **after** the `after` hooks. 

Example: 
```ruby
    before do
      I18n.locale = request.headers['Accept-Language']&.downcase&.to_sym || I18n.default_locale
    end

    after do
      # reset locale always after run. due to a missing `around` callback we reset it to the `default_locale` to avoid unexpected leaking in subsequent runs
      I18n.locale = I18n.default_locale
    end

    get 'something' do
      @units = Unit.all
      present @units, with: Entities::Unit
    end
```

Imagine we set `Accept-Language: en` as header and the default locale is `de`.

Inside `get 'something' do` the locale inside `I18n.locale` is `en` as expected and totally valid. Looking into the response body the payload is still **german** because the `after do` block is being executed **before** the GrapeEntity is rendered. Because iam resetting the locale to `de` in the `after` block the body payload is being rendered in german.

I dont have a solution for that yet but i believe there is no elegant one. Passing the locale in every Entity on every `present` call and evaluating it inside is not elegant at all. Forcing rendering manually inside the endpoint definition is neither. 

Any suggestions?

**Comment by thedarkside** [comment]
Oh wow, seems that appending `serializable: true` to the `present` call forces the evaluation of the Entity sooner and thus solves that but this isnt documented and i wonder if its possible to turn this on as default globally?

**Comment by dblock** [comment]
@thedarkside This looks at least unexpected, as you'd want `after` to be executed ... after. I think you should open a bug and try to write a spec in grape that reproduce this. 

Btw, I can't find where we force serialization when `serializable: true`, that would be good to have a reference to.

**Comment by thedarkside** [comment]
@dblock yes you are right. Its an issue related to grape-entity. The particular code is that one: 

```ruby
    def presented
      if options[:serializable]
        serializable_hash
      else
        self
      end
    end
```
Ill try to come up with a full report. Meanwhile the cleanest solution for me (means without polluting plenty of files to set this right) is to monkeypatch the above method to always return `serializable_hash` instead of `self`.
