### ISSUE TITLE
Release 1.3.3 => Nil handling

### ISSUE THREAD

**Issue by ericproulx** [ruby-grape/grape#2058]
Hello @dnesteryuk, thank you for the 1.3.3. release. Speaking of, I thought you would release a 1.4 since we made a significant change when handling nil values. I don't mind the 1.3.3 version but https://github.com/ruby-grape/grape/blob/master/UPGRADING.md shows >= 1.4 for the nils.

Thanks

**Comment by dnesteryuk** [comment]
@ericproulx Oh, I missed that :( We had 1.3.3 in the changelog, so I though it should be 1.3.3 :sob: 

@dblock Do you think we need to release 1.4.0?

**Comment by ericproulx** [comment]
No I’m not sure its worth it. Keep on the good work :)

**Comment by dblock** [comment]
I don't think it will help because 1.3.3 is out and I don't think we should yank it. I've corrected the version in UPGRADING in https://github.com/dblock/grape/commit/d8b66d5bc7ca5446137936a9e223547116e03da9. 

Let's make sure we ask to bump the version in backwards incompatible PRs before merging. This was probably my bad.
