### ISSUE TITLE
endpoints with same URL but different versions throws InvalidAcceptHeader on 0.11.0 w/ rescue_all

### ISSUE THREAD

**Issue by jpaas** [ruby-grape/grape#968]
I am mounting two versions v1 and v2, and I'm using the :header option. Two of the endpoints have the same URL /api/version.

In 0.10.1 I could select the correct version using the Accept header.
In 0.11.0 I can access v1(which is mounted first), but I can no longer select v2 (mounted second). It throws Grape::Exceptions::InvalidAcceptHeader.

**Comment by dblock** [comment]
Could you try building a test that reproduces this?

**Comment by mattsnyder** [comment]
Confirmed with 2 separate apps. When upgrading from 0.9 to 0.11 we receive this error on endpoints with multiple versions.

**Comment by mattsnyder** [comment]
Interesting, took one my projects where this was failing and stripped out all but the bare minimum and versioning works with both 0.9 and 0.11 using the header. See repo: https://github.com/mattsnyder/grape-versioning-example/tree/master

0.9 is the master and 0.11 is on a branch. Will try to investigate further.

**Comment by mattsnyder** [comment]
@dblock @jpaas I found it!! 

I began adding in behavior from my other apps that experienced this problem into this sample app and found it was when I added a `rescue_from :all` that the versioning broke.

So if you run the specs on the 0.11.0 branch a test will fail with:

```
1) GrapeVersioningExample::Endpoints::PingV1 GET /ping(version 1)
     Failure/Error: expect( async.response ).to include("version 1")
       expected "[:error, \"\\nProblem:\\n  Invalid accept header\\nResolution:\\n  API vendor or version not found.\"]" to include "version 1"
     # ./spec/api/ping_spec.rb:7:in `block (4 levels) in <top (required)>'
     # ./spec/api/ping_spec.rb:6:in `block (3 levels) in <top (required)>'
```

I'm guessing error handling is used for version handling??

**Comment by jpaas** [comment]
Yes I also have a `rescue_from :all`. Nice find!

**Comment by mattsnyder** [comment]
@jpaas Also found an interesting bug in https://github.com/mjackson/rack-accept that prohibits the use of `_` in the hypermedia type. And underscore is allowed per http://tools.ietf.org/html/rfc6838#page-4 section 4.2.

We're working on a PR for rack-accept to fix it.

**Comment by dblock** [comment]
Interesting, care to link a bug in rack-accept?

**Comment by dblock** [comment]
Also, again, we *want* a test in Grape for this.

**Comment by mattsnyder** [comment]
@dblock No issue filed with rack-accept yet. @jerrod is currently working on that end of things.

Any insight into the bug that @jpaas and I found with versioning?

**Comment by jerrod** [comment]
Here's the pull request for Rack-Accept -> https://github.com/mjackson/rack-accept/pull/17

FWIW this appears to be separate from the rescue :all issue @mattsnyder unearthed so perhaps we should split this discussion. I'd love to contribute some better specs to grape around header versioning.

**Comment by mattsnyder** [comment]
@dblock Any movement on this? Or an idea why/where this is occurring?

**Comment by dblock** [comment]
I don't have any additional insight into this :(

**Comment by jerrod** [comment]
This is caused by the issue demonstrated in https://github.com/intridea/grape/pull/1046

The mere presence of a rescue_all block breaks recognition of additional versions of endpoints.

Comment out the rescue block and the specs pass.  I have been unable to fix, but it appears to be an isse with the way rescues work in the `Middleware::Error.call!` method.

**Comment by dblock** [comment]
Very interesting, thanks for the repro @jerrod.

**Comment by romanlehnert** [comment]
Grape raises `Grape::Exceptions::InvalidAcceptHeader` with `cascade:  true`, when a routes does not match the requested version, to tell rack to try the next route. 

Isn't `rescue_from :all` expected to rescue from this exception?

**Comment by dblock** [comment]
I feel that yes, `rescue_from :all` should catch this as well.

**Comment by suan** [comment]
@romanlehnert @dblock But clearly we'd want the final behavior of having multiple-version-endpoints to work even if a `rescue_from :all` is present right? `rescue_from :all` shouldn't be catching _expected_ exceptions, especially exceptions needed for functionality.

We identified [the PR which caused this regression](https://github.com/ruby-grape/grape/pull/913), most specifically [this line](https://github.com/ruby-grape/grape/pull/913/files?diff=split#diff-fc867ab5863c687f310c0e69c11fc432L64)

We are attempting to put together a pull request to raise a different error when specifically the _version_ is invalid, and to pass that through so that Rack can do its thing, but we might not be able to do so while still keeping all the features introduced by the above linked PR...

**Comment by dblock** [comment]
Adding @croeck.

**Comment by croeck** [comment]
@dblock thx for adding me. I'll have a look into this during the next couple of days.

**Comment by suan** [comment]
@dblock @croeck Thanks for the quick reply!

https://github.com/ruby-grape/grape/pull/1114 has been created as a proposal solution. We tried to find a way to tell "are there any mounted versions to try after this?" but found no way to do so, hence we falled back to just _always_ letting an `InvalidVersionHeader` go through. Please let us know your thoughts.

**Comment by croeck** [comment]
OK, first my apologies to all affected by this issue which seems clearly related to my changes :disappointed: 

I looked into the issue as well as the proposed changes. Grape handles multiple versions via the `cascade=pass` header and leaves the actual work to the parent server, e.g. Rack.
With my changes the invalid versions were handled in the application as soon as there was a rescue handler, rather than passing the exceptions on. Therefore the cascading broke.

One idea worth considering might be to build a map of `alternative_versions`, for instance into the `options` of a `Route`. It could be done once during the initialization of the `Grape::API` and would have to regard the `params`, `path` and `method` to identify valid alternatives.
This information could then be used when raising or processing the exception. If there are (remaining) alternatives, the exception is not rescuable. Otherwise it could be processed by the rescue handlers.
